name: qonnect
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  permission_handler: ^12.0.0+1
  flutter_bloc: ^9.1.1
  toastification: ^3.0.2
  equatable: ^2.0.7
  dio: ^5.8.0
  socket_io_client: ^2.0.3+1
  sqflite_sqlcipher: ^3.1.0+1
  image_picker_linux: ^0.2.1+1
  connectivity_plus: ^6.1.4
  encrypt: ^5.0.3
  just_audio: ^0.9.41
  flutter_webrtc: ^0.14.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  uuid: ^4.5.1
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.1
  libsignal_protocol_dart:
    path: lib/utils/pqc/libsignalWithPqc_protocol_dart
  bcrypt:
  crypto:
  responsive_sizer: ^3.3.1
  mime: ^2.0.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - rootCA.crt
